services:
  api:
    build: ./api
    container_name: flask_app
    ports:
      - "5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://admin:dpSVtoZUjmyXAXWo6LfLe3NgzZQHPqvt3POhmMPTU2U@db:5432/database
    depends_on:
      - db
      - llm

  db:
    build: ./database
    container_name: postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dpSVtoZUjmyXAXWo6LfLe3NgzZQHPqvt3POhmMPTU2U
      - POSTGRES_DB=database
      # credentials could be stored elsewhere if better security is needed
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  llm:
    build: ./llm
    container_name: llm_service
    ports:
      - "6000"

volumes:
  postgres_data:
